---
abstract: "Do not escape all HTML entities\r"
author:
  - 'Renee Baecker <reneeb@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300039, CPAN::Meta::Converter version 2.132830'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: HTML-Template-Compiled-Plugins-RENEEB
requires:
  HTML::Entities: 0
  HTML::Template::Compiled: 0
resources:
  bugtracker: http://github.com/reneeb/HTML-Template-Compiled-Plugins-RENEEB/issues
  homepage: http://github.com/reneeb/HTML-Template-Compiled-Plugins-RENEEB
  repository: git://github.com/reneeb/HTML-Template-Compiled-Plugins-RENEEB.git
version: 0.02
